FROM apache/airflow:2.10.3

ENV AIRFLOW_HOME=/opt/airflow

# Set the user to root for administrative tasks
USER root

# Install system-level dependencies
RUN apt-get update -qq && apt-get install -y vim \
    && apt-get clean

# Switch to airflow user for Python package installations
USER ${AIRFLOW_UID}

# Copy and install Python dependencies as the airflow user
COPY requirements.txt .
RUN pip install --no-cache-dir "apache-airflow==2.10.3" -r requirements.txt \
    && pip install --no-cache-dir pandas sqlalchemy psycopg2-binary

# Set the shell options for better error handling
SHELL ["/bin/bash", "-o", "pipefail", "-e", "-u", "-x", "-c"]

# Return to root for further administrative tasks if needed
USER root

# Install Google Cloud SDK
ENV GCLOUD_HOME=/home/google-cloud-sdk
ENV PATH="${GCLOUD_HOME}/bin/:${PATH}"

RUN DOWNLOAD_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-darwin-arm.tar.gz" \
    && TMP_DIR="$(mktemp -d)" \
    && curl -fL "${DOWNLOAD_URL}" --output "${TMP_DIR}/google-cloud-sdk.tar.gz" \
    && mkdir -p "${GCLOUD_HOME}" \
    && tar xzf "${TMP_DIR}/google-cloud-sdk.tar.gz" -C "${GCLOUD_HOME}" --strip-components=1 \
    && "${GCLOUD_HOME}/install.sh" \
       --bash-completion=false \
       --path-update=false \
       --usage-reporting=false \
       --quiet \
    && rm -rf "${TMP_DIR}" \
    && gcloud --version

# Set the working directory and revert to airflow user
WORKDIR $AIRFLOW_HOME
USER ${AIRFLOW_UID}
